name: Run script

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  
concurrency:
  group: posts
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
    
      - name: Setup Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
      
      - name: Reset to main
        run: |
          git fetch origin
          git reset --hard origin/main

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Intall script tool
        run: dotnet tool install -g dotnet-script

      - name: Enumerate file list
        run: dotnet script Scripts/EnumerateFileList.csx Docs Docs.json --exclude-patterns template.md --strip-path ./
      
      - name: Commit file list
        run: |
          git add Docs.json
          git commit -m "게시글 목록 업데이트"
          git push -f